apiVersion: batch/v1
kind: CronJob
metadata:
  name: exemplo-cronjob
spec:
  schedule: "0 */6 * * *" # Executa a cada 6 horas
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tarefa
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "Executando tarefa agendada!"
          restartPolicy: OnFailure
